In [0]:
import numpy as np
import pandas as pd
from random import random

In [0]:
sample_data = [[0,0],
              [0,1],
              [1,0],
              [1,1]]

expected_results = [0,
                   1,
                   1,
                   1]

In [0]:
weights = np.random.random(2)/1000
weights

array([0.00033549, 0.00067861])

In [0]:
bias_weight = np.random.random()/1000
bias_weight

0.0008376115851445006

In [0]:
activation_threshold = 0.5
for iter_num in range(5):
  correct_answer = 0
  for idx, sample in enumerate(sample_data):
    input_vector = np.array(sample)
    weights = np.array(weights)
    activation_level = np.dot(input_vector, weights) + (bias_weights *1)
    if activation_level > activation_threshold:
      perceptron_output = 1
    else:
      perceptron_output = 0
    
    if perceptron_output == expected_results[idx]:
      correct_answer += 1
    new_weights = []
    print('Expected results: {}, perceptron_output :{}'.format(expected_results[idx], perceptron_output))
    for i, x in enumerate(sample):
      new_weights = weights + ((expected_results[idx] - perceptron_output) * x)
      print('old weight : {}, new weight : {} for sample {}'.format(weights, new_weights, sample))
    print('******' * 10)
    bias_weight = bias_weight + ((expected_results[idx] - perceptron_output) * 1)
    weights = np.array(new_weights)
    
  print('{} correct answers out of 4, for iteration {}'.format(correct_answer, iter_num))
  print('******' * 20)  
  

Expected results: 0, perceptron_output :0
old weight : [0.00033549 0.00067861], new weight : [0.00033549 0.00067861] for sample [0, 0]
old weight : [0.00033549 0.00067861], new weight : [0.00033549 0.00067861] for sample [0, 0]
************************************************************
Expected results: 1, perceptron_output :0
old weight : [0.00033549 0.00067861], new weight : [0.00033549 0.00067861] for sample [0, 1]
old weight : [0.00033549 0.00067861], new weight : [1.00033549 1.00067861] for sample [0, 1]
************************************************************
Expected results: 1, perceptron_output :1
old weight : [1.00033549 1.00067861], new weight : [1.00033549 1.00067861] for sample [1, 0]
old weight : [1.00033549 1.00067861], new weight : [1.00033549 1.00067861] for sample [1, 0]
************************************************************
Expected results: 1, perceptron_output :1
old weight : [1.00033549 1.00067861], new weight : [1.00033549 1.00067861] for sample [1, 1

XOR Keras Implementation

In [3]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

Using TensorFlow backend.


In [0]:
X_train = np.array([[0,0],
                   [0,1],
                   [1,0],
                   [1,1]])
y_train = np.array([[0],
                   [1],
                   [1],
                   [0]])

In [5]:
model = Sequential()
num_neurons = 10
model.add(Dense(num_neurons, input_dim=2))
model.add(Activation('tanh'))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.summary()




Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                30        
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [6]:
sgd = SGD(lr=0.1)
model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [7]:
# This is just doing metrix multiplication with the inputs to the random initialized weights with no knowledge of the output that is required.
model.predict(X_train)

array([[0.5       ],
       [0.34284735],
       [0.50247055],
       [0.359209  ]], dtype=float32)

In [8]:
model.fit(X_train,y_train, epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 56ms/step - loss: 0.7242 - acc: 0.7500
Epoch 2/100
4/4 [==============================] - 0s 1ms/step - loss: 0.7212 - acc: 0.5000
Epoch 3/100
4/4 [==============================] - 0s 1ms/step - loss: 0.7184 - acc: 0.5000
Epoch 4/100
4/4 [==============================] - 0s 886us/step - loss: 0.7160 - acc: 0.5000
Epoch 5/100
4/4 [==============================] - 0s 1ms/step - loss: 0.7137 - acc: 0.5000
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 0.7117 - acc: 0.5000
Epoch 7/100
4/4 [==============================] - 0s 1ms/step - loss: 0.7099 - acc: 0.5000
Epoch 8/100
4/4 [==============================] - 0s 2ms/step - loss: 0.7082 - acc: 0.5000
Epoch 9/100
4/4 [==============================] - 0s 2ms/step - loss: 0.7066 - acc: 0.5000
Epoch 10/100
4/4 [==============================] - 0s 1ms/step - loss: 0.7052 - acc: 0.5000
Epoch 11/100
4/4 [==============================] - 0s 1ms/step - loss: 0.70

In [9]:
model.predict(X_train)

array([[0.47572815],
       [0.5006464 ],
       [0.5476719 ],
       [0.47396696]], dtype=float32)

In [10]:
model.predict_classes(X_train)

array([[0],
       [1],
       [1],
       [0]], dtype=int32)

In [0]:
# Saved Trained Model
import h5py
model_structure = model.to_json()

with open("basic_model.json", "w") as json_file:
  json_file.write(model_structure)
  
model.save_weights("basic_weights.h5")